### ISSUE TITLE
Codesets and Keycodes are not accurate

### ISSUE THREAD

**Issue by andyslucky** [heathbar/vizio-smart-cast#11]
Maybe my television is a newer model or the OS is on a different version than these were tested on... but I have only gotten 20% of these Codesets and Keycodes to work. I had to correct almost all of them by hand and the Codesets for some keys dont even match the docs that this project seemed to be based on: [https://github.com/exiva/Vizio_SmartCast_API](url)

**Comment by heathbar** [comment]
If they don't match, them I'd guess you have a different model.

**Comment by benbasuni1** [comment]
I have a newer vizio TV I think.

RIGHT = [3, 7]
UP = [3, 8]

I will comment as much as I find out what the discrepancies are.

**Comment by kbrown01** [comment]
```
Event Name	     Codeset	   Code
Volume Down		5	          0
Volume Up		5	          1
Mute Off                5	          2
Mute On		        5	          3
Mute Toggle		5	          4
Cycle Input		7	          1
Power Off		11	          0 ** I use HA services for this and do not use the buttons
Power On		11	          1 ** I use HA services for this and do not use the buttons
Power Toggle	        11	          2 ** I use HA services for this and do not use the buttons
Down			3	          0
Left		        3	          1
Select		        3	          2
Up	                3	          8
Right			3	          7
Back	                4	          0
Exit	                9	          0
Menu			4	          8
Home			4	          3
```

**Comment by kbrown01** [comment]
What this should really have is someone to fork Vizio and implement a remote with code like this (which I use) right now as a REST command:

```
vizio_processkey:
  url: 'https://{{ ip }}:{{ port }}/key_command/'
  method: put
  content_type: "application/json"
  headers:
    AUTH: '{{ auth }}'
  payload: '{"KEYLIST": [{"CODESET": {{ codeset | int }},"CODE": {{ code | int }},"ACTION":"KEYPRESS"}]}'
  verify_ssl: false
```
Meaning we should have a service like "vizio.key_command" like we have "vizio.update_setting" (which frankly is mostly worhless and would have been the last thing I would implement)
